title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
remote_theme: pmarsceill/just-the-docs
permalink: pretty

url: https://plusplusone-documentation.github.io

