version: "3.1"
services:
  designer-basic-frontend:
    container_name: designer-basic-frontend
    build: ./
    ports:
      - "3000:3000"
    environment:
      - API_GRAPH_DESIGNER_SERVICE=http://localhost:8080
