version: "3.1"

services:
  designer-basic-frontend:
    container_name: designer-basic-frontend
    image: designer-basic
    ports:
      - "3000:3000"
    environment:
      - API_GRAPH_DESIGNER_SERVICE=http://localhost:8180/

  designer-basic-backend:
    container_name: designer-basic-backend
    image: kenstack-graph-designer-backend
    ports:
      - "8180:8080"
    environment:
      - NEO4J_URI=bolt://designer-neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASS=pass
      # - quarkus.log.level=DEBUG

  designer-neo4j:
    container_name: designer-neo4j
    image: designer-neo4j
    # user: "${UID}:${GID}"
    build:
      context: ..
      dockerfile: docker/neo4j/Dockerfile
    ports:
      - "7474:7474"
      - "7687:7687"
      - "5005:5005"
    volumes:
      - ./graph-designer/neo4j/data:/data
      - ./graph-designer/neo4j/import:/import
    environment:
      - NEO4J_AUTH=neo4j/pass
